CREATE DATABASE looker;

CREATE TABLE looker.channels (
    id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY,
    introduction BIGINT UNSIGNED NULL,
    jail BIGINT UNSIGNED NULL,
    log BIGINT UNSIGNED NULL,
    role BIGINT UNSIGNED NULL,
    verify BIGINT UNSIGNED NULL,
    welcome BIGINT UNSIGNED NULL
);

CREATE TABLE looker.quarantine (
    id BIGINT UNSIGNED NOT NULL,
    channel BIGINT UNSIGNED NOT NULL,
    user BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(channel, user)
);

CREATE TABLE looker.verify (
    id BIGINT UNSIGNED NOT NULL UNIQUE PRIMARY KEY,
    verified BIGINT UNSIGNED NULL,
    unverified BIGINT UNSIGNED NULL,
    permissions BIGINT UNSIGNED NOT NULL
);
