name: Cargo Clippy

on:
  - push

jobs:
  configure:
    container: rust:alpine
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Ensure apk packages
        run: apk --no-cache add musl-dev
  clippy:
    container: rust:alpine
    runs-on: ubuntu-latest
    steps:
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy
