name: Docker

on:
  - push

jobs:
  docker:
    container: rust:alpine
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure
        uses: ./.github/actions/configure
      - name: Clippy
        uses: ./.github/actions/clippy
      - name: Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push this ref
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.ref }}
      - name: Docker push latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          push: true
          tags: latest
