name: Lint

on:
  - push

jobs:
  clippy:
    container: rust:alpine
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure
        uses: ./.github/actions/configure
      - name: Clippy
        uses: ./.github/actions/clippy
